# -*- coding: utf-8 -*-
"""10_CNN_object_detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NzJIZoOGB9-NTSryXHCYVCnbprFHKj4c
"""

pip install ultralytics opencv-python

import cv2
import numpy as np
import matplotlib.pyplot as plt
from google.colab import files

# Step 2: Upload Image
uploaded = files.upload()

# Get uploaded image name
image_name = list(uploaded.keys())[0]

# Download YOLO model configuration and weights, and COCO labels
!wget https://pjreddie.com/media/files/yolov3.weights
!wget https://raw.githubusercontent.com/pjreddie/darknet/master/cfg/yolov3.cfg
!wget https://raw.githubusercontent.com/pjreddie/darknet/master/data/coco.names

# Step 4: Load class labels
with open("coco.names", "r") as f:
  classes = [line.strip() for line in f.readlines()]
# Step 5: Load YOLO network
net = cv2.dnn.readNet("yolov3.weights", "yolov3.cfg")
layer_names = net.getLayerNames()
output_layers = [layer_names[i - 1] for i in net.getUnconnectedOutLayers()]
# Step 6: Load image
image = cv2.imread(image_name)
height, width, channels = image.shape
# Step 7: Prepare image for CNN
blob = cv2.dnn.blobFromImage(image, 0.00392, (416,416), (0,0,0), True, crop=False)
net.setInput(blob)
# Step 8: Forward pass
outs = net.forward(output_layers)
# Step 9: Store detection results
boxes = []
confidences = []
class_ids = []
for out in outs:
    for detection in out:
        scores = detection[5:]
        class_id = np.argmax(scores)
        confidence = scores[class_id]
        if confidence > 0.5:
            center_x = int(detection[0]*width)
            center_y = int(detection[1]*height)
            w = int(detection[2]*width)
            h = int(detection[3]*height)
            x = int(center_x - w/2)
            y = int(center_y - h/2)
            boxes.append([x, y, w, h])
            confidences.append(float(confidence))
            class_ids.append(class_id)
# Step 10: Apply Non-Maximum Suppression
indexes = cv2.dnn.NMSBoxes(boxes, confidences, 0.5, 0.4)
# Step 11: Draw rectangles
if len(indexes) > 0:
    for i in indexes.flatten():
        x, y, w, h = boxes[i]
        label = str(classes[class_ids[i]])
        cv2.rectangle(image, (x,y), (x+w,y+h), (0,255,0), 2)
        cv2.putText(image, label, (x,y-10),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0,255,0), 2)
# Step 12: Show output
plt.figure(figsize=(10,6))
plt.imshow(cv2.cvtColor(image, cv2.COLOR_BGR2RGB))
plt.axis("off")
plt.show()

