# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NzJIZoOGB9-NTSryXHCYVCnbprFHKj4c
"""

import numpy as np
import matplotlib.pyplot as plt

# Input range
x = np.linspace(-10, 10, 100)

# Activation functions
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def tanh(x):
    return np.tanh(x)

def relu(x):
    return np.maximum(0, x)

def leaky_relu(x):
    return np.where(x > 0, x, 0.01 * x)

# Plotting
plt.figure(figsize=(10, 8))

plt.subplot(2, 2, 1)
plt.plot(x, sigmoid(x))
plt.title("Sigmoid")

plt.subplot(2, 2, 2)
plt.plot(x, tanh(x))
plt.title("Tanh")

plt.subplot(2, 2, 3)
plt.plot(x, relu(x))
plt.title("ReLU")

plt.subplot(2, 2, 4)
plt.plot(x, leaky_relu(x))
plt.title("Leaky ReLU")

plt.tight_layout()
plt.show()