# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NzJIZoOGB9-NTSryXHCYVCnbprFHKj4c
"""

import numpy as np

# Training data: ASCII values of digits 0–9
ascii_values = np.array([ord(str(i)) for i in range(10)])

# Normalize inputs
X = ascii_values / 100.0

# Targets: Even = 0, Odd = 1
y = np.array([i % 2 for i in range(10)])

# Initialize weights and bias
weight = np.random.rand()
bias = np.random.rand()

# Learning rate
lr = 0.1

# Activation function (step)
def step(x):
    return 1 if x >= 0 else 0

# Training
epochs = 20

for epoch in range(epochs):
    for i in range(len(X)):
        net = X[i] * weight + bias
        output = step(net)
        error = y[i] - output

        # Update rule
        weight += lr * error * X[i]
        bias += lr * error

# Testing
print("Digit | ASCII | Prediction (0=Even, 1=Odd)")
print("------------------------------------------")

for i in range(10):
    x = ord(str(i)) / 100.0
    net = x * weight + bias
    pred = step(net)
    print(f"  {i}   |  {ord(str(i))}   |      {pred}")