# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NzJIZoOGB9-NTSryXHCYVCnbprFHKj4c
"""

import numpy as np
import matplotlib.pyplot as plt

# Sample dataset (2D points)
# Class 0 (Blue)
X0 = np.array([[1, 1], [2, 1], [1.5, 2]])

# Class 1 (Red)
X1 = np.array([[4, 4], [5, 3], [4.5, 5]])

# Combine data
X = np.vstack((X0, X1))
y = np.array([0]*len(X0) + [1]*len(X1))

# Initialize weights and bias
w = np.random.rand(2)
b = np.random.rand()

# Learning rate
lr = 0.1

# Step activation
def step(z):
    return 1 if z >= 0 else 0

# Training
epochs = 20

for epoch in range(epochs):
    for i in range(len(X)):
        z = np.dot(w, X[i]) + b
        y_pred = step(z)
        error = y[i] - y_pred

        # Perceptron update rule
        w = w + lr * error * X[i]
        b = b + lr * error

# -----------------------------
# Plotting Decision Boundary
# -----------------------------

plt.figure(figsize=(8,6))

# Plot points
plt.scatter(X0[:,0], X0[:,1], color='blue', label='Class 0')
plt.scatter(X1[:,0], X1[:,1], color='red', label='Class 1')

# Decision boundary line
x_vals = np.linspace(0, 6, 100)

# Avoid division by zero
if w[1] != 0:
    y_vals = -(w[0]*x_vals + b) / w[1]
    plt.plot(x_vals, y_vals, 'k--', label='Decision Boundary')

# Labels
plt.xlabel("Feature 1")
plt.ylabel("Feature 2")
plt.title("Perceptron Decision Regions")
plt.legend()
plt.grid()

plt.show()