# -*- coding: utf-8 -*-
"""5_Bidirectional _Associative_Memory_twopairs_vectors.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NzJIZoOGB9-NTSryXHCYVCnbprFHKj4c
"""

import numpy as np

# Bipolar conversion (0 → -1, 1 → +1)
def to_bipolar(v):
    return np.where(v == 0, -1, 1)

# Sign activation function
def sign(x):
    return np.where(x >= 0, 1, -1)

# -----------------------------
# Define Pattern Pairs
# -----------------------------

# Pair 1
X1 = np.array([1, 0, 1])
Y1 = np.array([0, 1])

# Pair 2
X2 = np.array([0, 1, 0])
Y2 = np.array([1, 0])

# Convert to bipolar
X1 = to_bipolar(X1)
Y1 = to_bipolar(Y1)
X2 = to_bipolar(X2)
Y2 = to_bipolar(Y2)

# -----------------------------
# Training (Weight Matrix)
# -----------------------------

W = np.outer(X1, Y1) + np.outer(X2, Y2)

print("Weight Matrix W:")
print(W)

# -----------------------------
# Recall Function
# -----------------------------

def recall(X_input, W, steps=5):
    X = X_input.copy()

    for _ in range(steps):
        # Forward: X → Y
        Y = sign(np.dot(X, W))

        # Backward: Y → X
        X = sign(np.dot(Y, W.T))

    return X, Y

# -----------------------------
# Testing
# -----------------------------

print("\nTesting BAM\n")

# Test with X1
print("Input X1:", X1)
X_out, Y_out = recall(X1, W)
print("Recalled Y:", Y_out)

# Test with X2
print("\nInput X2:", X2)
X_out, Y_out = recall(X2, W)
print("Recalled Y:", Y_out)