# -*- coding: utf-8 -*-
"""6_ recognize_5 * 3 matrix.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NzJIZoOGB9-NTSryXHCYVCnbprFHKj4c
"""

import numpy as np

# -----------------------------
# Step 1: Define Digits (5x3)
# -----------------------------

digits = {
    "0": [
        [1,1,1],
        [1,0,1],
        [1,0,1],
        [1,0,1],
        [1,1,1]
    ],
    "1": [
        [0,1,0],
        [1,1,0],
        [0,1,0],
        [0,1,0],
        [1,1,1]
    ],
    "2": [
        [1,1,1],
        [0,0,1],
        [1,1,1],
        [1,0,0],
        [1,1,1]
    ],
    "3": [
        [1,1,1],
        [0,0,1],
        [0,1,1],
        [0,0,1],
        [1,1,1]
    ],
    "9": [
        [1,1,1],
        [1,0,1],
        [1,1,1],
        [0,0,1],
        [1,1,1]
    ]
}

# Flatten 5x3 → 15 vector
def flatten(matrix):
    return np.array(matrix).flatten()

# -----------------------------
# Step 2: Prepare Training Data
# -----------------------------

X = []
y = []

labels = ["0", "1", "2", "3", "9"]

for idx, key in enumerate(labels):
    X.append(flatten(digits[key]))
    y.append(idx)

X = np.array(X)
y = np.array(y)

# -----------------------------
# Step 3: Initialize Weights
# -----------------------------

num_classes = len(labels)
num_features = 15

W = np.random.randn(num_classes, num_features)
b = np.zeros(num_classes)

lr = 0.1
epochs = 50

# -----------------------------
# Step 4: Training
# -----------------------------

for epoch in range(epochs):
    for i in range(len(X)):
        xi = X[i]
        target = y[i]

        # Compute scores
        scores = np.dot(W, xi) + b

        # Predicted class
        pred = np.argmax(scores)

        # Update if wrong
        if pred != target:
            W[target] += lr * xi
            W[pred] -= lr * xi
            b[target] += lr
            b[pred] -= lr

# -----------------------------
# Step 5: Testing
# -----------------------------

def predict(x):
    scores = np.dot(W, x) + b
    return np.argmax(scores)

print("Testing Recognition:\n")

for i in range(len(X)):
    pred = predict(X[i])
    print(f"Actual: {labels[y[i]]}  Predicted: {labels[pred]}")

