# -*- coding: utf-8 -*-
"""7_  BackPropagation_Network_XOR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NzJIZoOGB9-NTSryXHCYVCnbprFHKj4c
"""

import numpy as np

# Sigmoid activation
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Derivative of sigmoid
def sigmoid_derivative(x):
    return x * (1 - x)

# -----------------------------
# Step 1: Input and Output
# -----------------------------

X = np.array([
    [0,0],
    [0,1],
    [1,0],
    [1,1]
])

y = np.array([[0], [1], [1], [0]])

# -----------------------------
# Step 2: Initialize Weights
# -----------------------------

np.random.seed(42)

# 2 input → 2 hidden
W1 = np.random.rand(2, 2)
b1 = np.random.rand(1, 2)

# 2 hidden → 1 output
W2 = np.random.rand(2, 1)
b2 = np.random.rand(1, 1)

lr = 0.5
epochs = 10000

# -----------------------------
# Step 3: Training (Backprop)
# -----------------------------

for epoch in range(epochs):

    # Forward pass
    hidden_input = np.dot(X, W1) + b1
    hidden_output = sigmoid(hidden_input)

    final_input = np.dot(hidden_output, W2) + b2
    final_output = sigmoid(final_input)

    # Error
    error = y - final_output

    # Backward pass
    d_output = error * sigmoid_derivative(final_output)

    error_hidden = np.dot(d_output, W2.T)
    d_hidden = error_hidden * sigmoid_derivative(hidden_output)

    # Update weights
    W2 += np.dot(hidden_output.T, d_output) * lr
    b2 += np.sum(d_output, axis=0, keepdims=True) * lr

    W1 += np.dot(X.T, d_hidden) * lr
    b1 += np.sum(d_hidden, axis=0, keepdims=True) * lr

# -----------------------------
# Step 4: Testing
# -----------------------------

print("XOR Results:\n")

for i in range(len(X)):
    hidden = sigmoid(np.dot(X[i], W1) + b1)
    output = sigmoid(np.dot(hidden, W2) + b2)
    print(f"Input: {X[i]} → Output: {output[0][0]:.4f}")