# -*- coding: utf-8 -*-
"""8_ Back_Propagation_Feed-forward_neural _network .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NzJIZoOGB9-NTSryXHCYVCnbprFHKj4c
"""

import numpy as np

# -----------------------------
# Activation Functions
# -----------------------------

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

# -----------------------------
# Feedforward Neural Network
# -----------------------------

class NeuralNetwork:
    def __init__(self, input_size, hidden_size, output_size, lr=0.5):
        # Initialize weights and biases
        self.W1 = np.random.rand(input_size, hidden_size)
        self.b1 = np.random.rand(1, hidden_size)

        self.W2 = np.random.rand(hidden_size, output_size)
        self.b2 = np.random.rand(1, output_size)

        self.lr = lr

    def forward(self, X):
        # Input → Hidden
        self.z1 = np.dot(X, self.W1) + self.b1
        self.a1 = sigmoid(self.z1)

        # Hidden → Output
        self.z2 = np.dot(self.a1, self.W2) + self.b2
        self.a2 = sigmoid(self.z2)

        return self.a2

    def backward(self, X, y, output):
        # Output layer error
        error = y - output
        d_output = error * sigmoid_derivative(output)

        # Hidden layer error
        error_hidden = np.dot(d_output, self.W2.T)
        d_hidden = error_hidden * sigmoid_derivative(self.a1)

        # Update weights and biases
        self.W2 += np.dot(self.a1.T, d_output) * self.lr
        self.b2 += np.sum(d_output, axis=0, keepdims=True) * self.lr

        self.W1 += np.dot(X.T, d_hidden) * self.lr
        self.b1 += np.sum(d_hidden, axis=0, keepdims=True) * self.lr

    def train(self, X, y, epochs=10000):
        for epoch in range(epochs):
            output = self.forward(X)
            self.backward(X, y, output)

    def predict(self, X):
        output = self.forward(X)
        return np.round(output)

# -----------------------------
# Example: XOR Problem
# -----------------------------

if __name__ == "__main__":

    # Input (XOR)
    X = np.array([
        [0,0],
        [0,1],
        [1,0],
        [1,1]
    ])

    # Output
    y = np.array([
        [0],
        [1],
        [1],
        [0]
    ])

    # Create network
    nn = NeuralNetwork(input_size=2, hidden_size=2, output_size=1)

    # Train
    nn.train(X, y, epochs=10000)

    # Test
    print("Predictions:")
    for i in range(len(X)):
        pred = nn.predict(X[i])
        print(f"Input: {X[i]} → Output: {int(pred[0][0])}")

